config/routes.rb
Vpapp::Application.routes.draw do

  resources :countries

  resources :states

  resources :cities

  resources :student_talukas

  resources :student_districts

  resources :yearly_detail_streams

  resources :yearly_detail_courses

  resources :yearly_detail_years

  resources :donor_titles

  resources :donation_purposes

  resources :donation_types

  resources :donation_statuses

  resources :donor_types

  resources :student_area_types

  resources :student_parent_occupations

  resources :student_study_meds

  resources :student_categories

  resources :student_castes

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :donation_year_links

  resources :yearly_details do
    get "upload_yeardata", :on => :collection
    get "upload_validate_yeardata", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "upload_yeardata", :on => :collection
    post "upload_validate_yeardata", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :yearly_details

  get "users/index"
  get "users/new"
  get "users/show"
  get "users/edit"

  resources :students do
    get "upload_student", :on => :collection
    get "upload_validate_student", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_student", :on => :collection
    post "upload_validate_student", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :students

  resources :donations do
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :donations

  get "home/choosepage"

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  devise_for :users
  resources :users

  devise_scope :user do
    get 'users/sign_out', :to => 'devise/sessions#destroy', as: 'destroy_user_session'
  end

  resources :donors do
    get "upload_donor", :on => :collection
    get "upload_validate_donor", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_donor", :on => :collection
    post "upload_validate_donor", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :donors

  get "home/index"

  root :to => 'home#index'

  match ':action' => 'home#:action'
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  # Donor has many donations
  has_many :donations, :dependent => :destroy

  # First Name and Last name needed for Donors which should be unique
  validates_presence_of :first_name, :last_name
  validates :first_name, :uniqueness => { :scope => :last_name}

  # Pagination
  paginates_per 5

  # Search first and last name together for reporting and filtering
  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||', parent.table[:first_name], ' '),
      parent.table[:last_name])
  end

end

app/models/donor_type.rb
class DonorType < ActiveRecord::Base
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # CanCan Specific Authorization. Doesn't need instance variables
  # See all first line for actions commented except index
  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /donors
  # GET /donors.json
  def index
  # @donors = Donor.all
    # Paginated Output with Kaminari
    @donors = Donor.order(:created_at).page params[:page]
    @all_donors = Donor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
      format.xls {
              send_data @all_donors.to_xls(:name => "Donors",
              # :columns => [:name, :address, :age],
              # :headers => ['NAME', 'ADDRESS', 'AGE'],
              :cell_format => {:color => :blue},
              :header_format => {:weight => :bold, :color => :red}),
              :filename => 'All_Donors.xls' }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  # @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
  # @donor = Donor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
  # @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.json
  def create
  # @donor = Donor.new(params[:donor])

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
  # @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
  # @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :ok }
    end
  end

  # Upload and Validate Donor from Excel File
  def upload_validate_donor
    donor_file = params[:excel_file]
    file = ExcelUploader.new
    file.store!(donor_file)
    book = Spreadsheet.open "#{file.store_path}"
    sheet1 = book.worksheet 0
    @donors = []
    @errors = Hash.new
    @counter = 0

    sheet1.each 1 do |row|
      @counter+=1
      cur_donor = Donor.new
      # Populate Fields
      cur_donor.ser_no = row[0]
      cur_donor.title = row[1]
      cur_donor.first_name = row[2]

      # Last Name formatting
      if row[3].blank?
        cur_donor.last_name = "."
      else
        cur_donor.last_name = row[3]
      end

      # Gender format changes
      if ((row[4] == "B") || (row[4] == "Boy") || (row[4] == "M") || (row[4] == "Male"))
        cur_donor.gender = "Male"
      elsif ((row[4] == "G") || (row[4] == "Girl") || (row[4] == "F") || (row[4] == "Female"))
        cur_donor.gender = "Female"
      else
        cur_donor.gender = row[4]
      end

      cur_donor.email = row[5]
      cur_donor.address_first_line = row[6]
      cur_donor.address_second_line = row[7]
      cur_donor.address_landmark = row[8]
      cur_donor.district = row[9]
      cur_donor.city = row[10]
      cur_donor.state = row[11]
      cur_donor.country = row[12]
      cur_donor.pincode = row[13]
      cur_donor.phone = row[14].to_s
      cur_donor.mobile = row[15].to_s.to_s
      cur_donor.donor_type = row[16]
      cur_donor.comment = row[17]

      if cur_donor.valid?
        @donors << cur_donor
        # Save the data to DB on success validation for each entry
        cur_donor.save
      else
        @errors["#{@counter+1}"] = cur_donor.errors
      end
    end
    file.remove!
  end

  # Search and Find relevant records based on query
  # Implemented using ransack gem
  # Before calling the form page, new object of Ransack::Search
  # for specific model needs to be created
  def search
    @search = Ransack::Search.new(Donor)
  end

  # Search Results
  def search_results
    @search = Donor.search(params[:q])
    @donors = @search.result(:distinct => true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
      format.xls {
              send_data @donors.to_xls(:name => "Found_Donors",
              # :columns => [:name, :address, :age],
              # :headers => ['NAME', 'ADDRESS', 'AGE'],
              :cell_format => {:color => :blue},
              :header_format => {:weight => :bold, :color => :red}),
              :filename => 'Found_Donors.xls' }
    end
  end

  # Destroy all records
  def remove_all_records
    Donor.destroy_all

    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'All Donors deleted successfully.' }
      format.json { head :ok }
    end
  end

end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_donation_index.html.erb
<fieldset>
<legend> Your Donations</legend>

<table id="donations">
  <tr>
    <th>ID</th>
    <th>Amount</th>
    <th>Status</th>
    <th>Donation Type</th>
    <th>Purpose</th>
    <th>Donated At</th>
    <th>Comment</th>
    <% if can? :update, Donation %>
      <th>Actions</th>
    <% end %>
  </tr>

<% donations.each do |donation| %>
  <tr>
    <td><%= donation.id %></td>
    <td><%= donation.amount %></td>
    <td><%= donation.status %></td>
    <td><%= donation.donation_type %></td>
    <td><%= donation.purpose %></td>
    <td><%= donation.donation_date %></td>
    <td><%= donation.comment %></td>
    <% if can? :update, Donation %>
      <td>
      <%= link_to 'Edit', edit_donation_path(donation) %>
      <% if can? :destroy, Donation %>
        | <%= link_to 'Destroy', donation, confirm: 'Are you sure?', method: :delete %>
      <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

</fieldset>

<br />

app/views/donors/_donation_new.html.erb
<%= form_for(donation) do |f| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
<legend> Add New Donation</legend>
  <%= f.hidden_field :donor_id %>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :purpose %>
    <%= f.collection_select :purpose,
        DonationPurpose.all(:order => 'donation_purpose'),
        :donation_purpose, :donation_purpose,
        :prompt => "Select Purpose", :include_blank => true %>
  </div>
  <%-# Status and Type should be visible only to admins -%>
  <% if can? :create, Donation %>
    <div class="field">
      <%= f.label :status %>
      <%= f.collection_select :status,
          DonationStatus.all(:order => 'donation_status'), :donation_status, :donation_status,
          :prompt => "Select Status", :include_blank => true %>
    </div>
    <div class="field">
      <%= f.label :donation_type %>
      <%= f.collection_select :donation_type,
          DonationType.all(:order => 'donation_type'), :donation_type, :donation_type,
          :prompt => "Select Type", :include_blank => true %>
    </div>
  <% else %>
    <%= f.hidden_field :status, :value => "Donated" %>
    <%= f.hidden_field :donation_type, :value => "Online" %>
  <% end %>
  <div class="field">
    <%= f.label :donation_date %>
    <%= f.date_select :donation_date,
    		:start_year => 2001, :end_year => Time.now.year + 1,
        :order => [:day, :month, :year],
        :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit "Add Donation" %>
  </div>
</fieldset>
<% end %>

app/views/donors/_student_index.html.erb
<fieldset>
<legend> Your Linked Students</legend>

<table id="donations">
  <tr>
    <th>District</th>
    <th>Taluka</th>
    <th>VP ID</th>
    <th>Student Name</th>
    <th>Father Name</th>
    <th>Date of birth</th>
  </tr>

<% students.each do |student| %>
  <tr>
    <td><%= student.district %></td>
    <td><%= student.taluka %></td>
    <td><%= student.vp_id %></td>
    <td><%= link_to "#{student.first_name} #{student.last_name}", student %></td>
    <td><%= student.father_name %></td>
    <td><%= student.date_of_birth %></td>
  </tr>
<% end %>
</table>
</fieldset>
<br />

app/views/donors/edit.html.erb
<h1>CHANGE DONOR INFORMATION FOR
<%= @donor.first_name %> <%= @donor.last_name %>
<% if (user_signed_in?) && (current_user.role == "super_admin") %>
ID: <%= @donor.id %>
<% end %>
</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', :back %>

app/views/donors/index.html.erb
<h1>LISTING ALL DONORS INFORMATION</h1>

<%= link_to "Upload Donors", upload_donor_donors_path %>

<%= link_to 'Export to EXCEL', donors_path(request.parameters.merge({:format => :xls})) %>

<% if can? :create, Donor %>
  <%= link_to 'Add New Donor', new_donor_path %>
<% end %>

<% if user_signed_in? && current_user.role == "super_admin" %>
  <%= link_to 'DESTROY ALL', remove_all_records_donors_path, confirm: 'Are you sure?  Records once deleted cannot be recovered by any means.' %>
<% end %>

<hr />
<%= paginate @donors %>
<hr />

<table id="donors">
  <tr>
    <th>Donor Details</th>
    <th>Contact Details</th>
    <th>Address Details</th>
    <% if can? :update, Donor %>
      <th>Actions</th>
    <% end %>
  </tr>

<% @donors.each do |donor| %>
  <!-- Only show the list of donors for the current user -->
  <!-- But all needs to be shown for admin and moderator -->
  <% if (user_signed_in?) && (can? :read, donor) %>

  <tr onMouseOver="this.className='highlight'" onMouseOut="this.className='normal'">
    <td>
       <table id="container">
          <tr>
          <td>Name:</td>
          <td colspan="4"><%= link_to "#{donor.title} #{donor.first_name} #{donor.last_name}", donor %></td>
          </tr>
          <tr>
          <td>DOB:</td>
          <td colspan="4"><%= donor.date_of_birth %></td>
          </tr>
          <tr>
          <td>Donor Type:</td>
          <td colspan="4"><%= donor.donor_type %></td>
          </tr>
          <tr>
          <td>Gender:</td>
          <td><%= donor.gender %></td>
          <td colspan="2">Anonymous:</td>
          <td><%= donor.anonymous %></td>
          </tr>
       </table>
    </td>
    <td>
       <table id="container">
          <tr>
          <td>Email:</td>
          <td colspan="4"><%= donor.email %></td>
          </tr>
          <tr>
          <td>Phone:</td>
          <td><%= donor.phone %></td>
          <td>Mobile:</td>
          <td><%= donor.mobile %></td>
          </tr>
          <tr>
          <td>District:</td>
          <td colspan="4"><%= donor.district %></td>
          </tr>
          <tr>
          <td>Comment:</td>
          <td colspan="4"><%= donor.comment %></td>
          </tr>
       </table>
    </td>
    <td>
       <table id="container">
          <tr>
          <td>Address Line1:</td>
          <td colspan="5"><%= donor.address_first_line %></td>
          </tr>
          <tr>
          <td>Address Line2:</td>
          <td colspan="5"><%= donor.address_second_line %></td>
          </tr>
          <tr>
          <td>Landmark:</td>
          <td colspan="4"><%= donor.address_landmark %></td>
          </tr>
          <tr>
          <td><%= donor.city %></td>
          <td colspan="2"><%= donor.state %></td>
          <td><%= donor.country %></td>
          <td><%= donor.pincode %></td>
          </tr>
       </table>
    </td>
    <% if can? :update, Donor %>
      <td>
      <%= link_to 'Edit', edit_donor_path(donor) %>
      <% if can? :destroy, Donor %>
        | <%= link_to 'Destroy', donor, confirm: 'Are you sure?', method: :delete %>
      <% end %>
      </td>
    <% end %>
  <tr>

    <% end %>

<% end %>
</table>
<hr />

app/views/donors/new.html.erb
<h1>ADD NEW DONOR INFORMATION</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/donors/search.html.erb
<h1>Search and Find Donors </h1>
<h4 id="alert">Leave fields blank if you don't want them to be used for search</h4>
<%= search_form_for @search, url: search_results_donors_path do |f| %>
<fieldset>
<legend>Personal Attributes</legend>
  <%= f.label "Name Contains" %>
  <%= f.text_field :first_name_or_last_name_cont %>
  <%= f.label :email_cont %>
  <%= f.text_field :email_cont %>
  <%= f.label :gender_cont %>
  <%= f.text_field :gender_cont %>
  Donor Type Matches
  <%# <%= f.label :donor_type_eq %>
  <%= f.select(:donor_type_eq, %w{Individual VP_Alumni Institution Company Volunteer Overseas}, :include_blank => true) %>
</fieldset>

<fieldset>
<legend>Location Attributes</legend>
  <%= f.label :district_start %>
  <%= f.text_field :district_start %>
  <%= f.label :city_start %>
  <%= f.text_field :city_start %>
  <%= f.label :state_start %>
  <%= f.text_field :state_start %>
  <%= f.label :country_start %>
  <%= f.text_field :country_start %>
</fieldset>

  <%= f.submit %>
<% end %>

app/views/donors/search_results.html.erb
<h1>DONOR SEARCH RESULTS</h1>

<%= link_to 'Export to EXCEL', search_results_donors_path(request.parameters.merge({:format => :xls})) %>
<br />
<% if current_user.role == "super_admin" %>
  QUERY: <%= @donors.to_sql %>
<% end %>
<hr />

<table id="donors">
  <tr>
    <th>Donor Details</th>
    <th>Contact Details</th>
    <th>Address Details</th>
    <th>Actions</th>
  </tr>

<% @donors.each do |donor| %>
  <!-- Only show the list of donors for the current user -->
  <!-- But all needs to be shown for admin and moderator -->
  <% if (user_signed_in?) && (can? :read, donor) %>

  <!-- <tr onMouseOver="this.className='highlight'" onMouseOut="this.className='normal'"> -->
  <tr>
    <td>
       <table id="container">
          <tr>
          <td>Name:</td>
          <td colspan="4"><%= donor.title %> <%= donor.first_name %> <%= donor.last_name %></td>
          </tr>
          <tr>
          <td>DOB:</td>
          <td colspan="4"><%= donor.date_of_birth %></td>
          </tr>
          <tr>
          <td>Donor Type:</td>
          <td colspan="4"><%= donor.donor_type %></td>
          </tr>
          <tr>
          <td>Gender:</td>
          <td><%= donor.gender %></td>
          <td colspan="2">Anonymous:</td>
          <td><%= donor.anonymous %></td>
          </tr>
       </table>
    </td>
    <td>
       <table id="container">
          <tr>
          <td>Email:</td>
          <td colspan="4"><%= donor.email %></td>
          </tr>
          <tr>
          <td>Phone:</td>
          <td><%= donor.phone %></td>
          <td>Mobile:</td>
          <td><%= donor.mobile %></td>
          </tr>
          <tr>
          <td>District:</td>
          <td colspan="4"><%= donor.district %></td>
          </tr>
          <tr>
          <td>Comment:</td>
          <td colspan="4"><%= donor.comment %></td>
          </tr>
       </table>
    </td>
    <td>
       <table id="container">
          <tr>
          <td>Address Line1:</td>
          <td colspan="5"><%= donor.address_first_line %></td>
          </tr>
          <tr>
          <td>Address Line2:</td>
          <td colspan="5"><%= donor.address_second_line %></td>
          </tr>
          <tr>
          <td>Landmark:</td>
          <td colspan="4"><%= donor.address_landmark %></td>
          </tr>
          <tr>
          <td><%= donor.city %></td>
          <td colspan="2"><%= donor.state %></td>
          <td><%= donor.country %></td>
          <td><%= donor.pincode %></td>
          </tr>
       </table>
    </td>
    <td>
        <%= link_to 'Show', donor %>

        <% if can? :update, donor %>
          | <%= link_to 'Edit', edit_donor_path(donor) %>
        <% end %>
        <% if can? :destroy, donor %>
          | <%= link_to 'Destroy', donor, confirm: 'Are you sure?', method: :delete %>
        <% end %>
    </td>
  <tr>

    <% end %>

<% end %>
</table>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
SHOWING DONOR:
<%= @donor.first_name %> <%= @donor.last_name %>
<% if (user_signed_in?) && (current_user.role == "super_admin") %>
ID: <%= @donor.id %>
<% end %>
</h1>
<h3 id="alert">NOTE: You cannot change any Profile information here. However, you can DONATE newly</h3>

<%= form_for(@donor) do |f| %>
<fieldset>
<legend>Personal Information</legend>
  <div class="field">
    <%= f.label :ser_no %>
    <%= f.text_field :ser_no, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :donor_type %><br />
    <%= f.text_field :donor_type, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender, :disabled => true %>
  </div>
  <br />
  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.text_field :date_of_birth, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label "Suite/Apt No." %>
    <%= f.text_field :address_first_line, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label "Street/Road" %>
    <%= f.text_field :address_second_line, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label "Landmark" %>
    <%= f.text_field :address_landmark, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label "District" %>
    <%= f.text_field :district, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, :disabled => true %>
    <%= f.label :state %>
    <%= f.text_field :state, :disabled => true %>
    <%= f.label :country %>
    <%= f.text_field :country, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :mobile, :disabled => true %>
  </div>
</fieldset>

<fieldset>
<legend> Want to remain Anonymous?</legend>
    <div class="field">
    <%= f.check_box :anonymous, :disabled => true %>
    I want to remain Anonymous. I do not want my information to be shown publically.
  </div>
</fieldset>

<fieldset>
<legend> Your Comment Here</legend>
  <div class="field">
    <%= f.text_area :comment, :disabled => true %>
  </div>
</fieldset>
<% end %>

<% if can? :update, Donor %>
  <%= link_to 'Edit', edit_donor_path(@donor) %> |
<% end %>
<%= link_to 'Back', :back %>

<%= render :partial => 'donation_index', :locals => {:donations=>@donor.donations} %>
<% if can? :create, Donation %>
  <%= render :partial => 'donation_new', :locals => {:donation=>Donation.new(:donor_id => @donor.id)} %>
<% end %>

<%# Get the list of all unique students for this donor using the below logic -%>
<% all_donations = @donor.donations %>
<% all_student_ids = [] %>
<% all_donations.each do |this_donation| %>
  <% all_yearly_details = this_donation.yearly_details %>
  <% all_yearly_details.each do |this_yearly_detail| %>
    <% unless all_student_ids.include?(this_yearly_detail.student_id) %>
      <% all_student_ids << this_yearly_detail.student_id %>
    <% end %>
  <% end %>
<% end %>

<%= render :partial => 'student_index', :locals => {:students=>Student.find_all_by_id(all_student_ids).uniq} %>

app/views/donors/upload_donor.html.erb
<fieldset>
<legend>Upload Donor</legend>
	<h3> Choose Upload file</h3>
	<h4>Uploads, Parses, Validates and stores the Donors Data in DB</h4>
	<%= form_tag('/donors/upload_validate_donor', :multipart => true) %>
	<p>
		<%= file_field_tag 'excel_file' %>
	</p>
	<p>
		<%= submit_tag "Start Upload" %>
	</p>
	</form>
</fieldset>

app/views/donors/upload_validate_donor.html.erb
<%= link_to 'All Donors', donors_path %>

<% unless @errors.empty? %>
<h1>Failure Entries</h1>
				<ul>
					<% @errors.each do |error| %>
					<li>
						Problems in line number <%= error[0] %>:
						<% error[1].full_messages.each do |msg|%>
						<p><%= msg %> </p>
						<%end%>
					</li>

				<% end %>
				</ul>
<%else%>
<h1>ALL SUCCESS</h1>
<% end %>
<h1>Success Entries</h1>
<table id="donations">
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Email</th>
    <th>Address</th>
    <th>District</th>
    <th>More Address</th>
    <th>Phone</th>
    <th>Type</th>
    <th>Comment</th>
  </tr>

<% @donors.each do |donor| %>
  <tr>
    <td><%= donor.title %> <%= donor.first_name %> <%= donor.last_name %></td>
    <td><%= donor.gender %></td>
    <td><%= donor.email %></td>
    <td>
      <%= donor.address_first_line %>,
      <%= donor.address_second_line %>,
      <%= donor.address_landmark %>
    </td>
    <td><%= donor.district %></td>
    <td><%= donor.city %> <%= donor.state %> <%= donor.country %> <%= donor.pincode %></td>
    <td><%= donor.phone %> <%= donor.mobile %></td>
    <td><%= donor.donor_type %></td>
    <td><%= donor.comment %></td>
  </tr>
<% end %>
</table>