config/routes.rb
Vpapp::Application.routes.draw do

  resources :countries

  resources :states

  resources :cities

  resources :student_talukas

  resources :student_districts

  resources :yearly_detail_streams

  resources :yearly_detail_courses

  resources :yearly_detail_years

  resources :donor_titles

  resources :donation_purposes

  resources :donation_types

  resources :donation_statuses

  resources :donor_types

  resources :student_area_types

  resources :student_parent_occupations

  resources :student_study_meds

  resources :student_categories

  resources :student_castes

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :donation_year_links

  resources :yearly_details do
    get "upload_yeardata", :on => :collection
    get "upload_validate_yeardata", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "upload_yeardata", :on => :collection
    post "upload_validate_yeardata", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :yearly_details

  get "users/index"
  get "users/new"
  get "users/show"
  get "users/edit"

  resources :students do
    get "upload_student", :on => :collection
    get "upload_validate_student", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_student", :on => :collection
    post "upload_validate_student", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :students

  resources :donations do
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :donations

  get "home/choosepage"

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  devise_for :users
  resources :users

  devise_scope :user do
    get 'users/sign_out', :to => 'devise/sessions#destroy', as: 'destroy_user_session'
  end

  resources :donors do
    get "upload_donor", :on => :collection
    get "upload_validate_donor", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_donor", :on => :collection
    post "upload_validate_donor", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :donors

  get "home/index"

  root :to => 'home#index'

  match ':action' => 'home#:action'
end

app/models/student_caste.rb
class StudentCaste < ActiveRecord::Base
end

app/controllers/student_castes_controller.rb
class StudentCastesController < ApplicationController
  # CanCan Specific Authorization. Doesn't need instance variables
  # See all first line for actions commented except index
  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /student_castes
  # GET /student_castes.json
  def index
  #  @student_castes = StudentCaste.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_castes }
    end
  end

  # GET /student_castes/1
  # GET /student_castes/1.json
  def show
  #  @student_caste = StudentCaste.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_caste }
    end
  end

  # GET /student_castes/new
  # GET /student_castes/new.json
  def new
  #  @student_caste = StudentCaste.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_caste }
    end
  end

  # GET /student_castes/1/edit
  def edit
  #  @student_caste = StudentCaste.find(params[:id])
  end

  # POST /student_castes
  # POST /student_castes.json
  def create
  #  @student_caste = StudentCaste.new(params[:student_caste])

    respond_to do |format|
      if @student_caste.save
        format.html { redirect_to @student_caste, notice: 'Student caste was successfully created.' }
        format.json { render json: @student_caste, status: :created, location: @student_caste }
      else
        format.html { render action: "new" }
        format.json { render json: @student_caste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_castes/1
  # PUT /student_castes/1.json
  def update
  #  @student_caste = StudentCaste.find(params[:id])

    respond_to do |format|
      if @student_caste.update_attributes(params[:student_caste])
        format.html { redirect_to @student_caste, notice: 'Student caste was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_caste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_castes/1
  # DELETE /student_castes/1.json
  def destroy
  #  @student_caste = StudentCaste.find(params[:id])
    @student_caste.destroy

    respond_to do |format|
      format.html { redirect_to student_castes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/student_castes_helper.rb
module StudentCastesHelper
end

app/views/student_castes/_form.html.erb
<%= form_for(@student_caste) do |f| %>
  <% if @student_caste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_caste.errors.count, "error") %> prohibited this student_caste from being saved:</h2>

      <ul>
      <% @student_caste.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caste_name %><br />
    <%= f.text_field :caste_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_castes/edit.html.erb
<h1>Editing student_caste</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_caste %> |
<%= link_to 'Back', student_castes_path %>

app/views/student_castes/index.html.erb
<h1>Listing student_castes</h1>

<table>
  <tr>
    <th>Caste name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_castes.each do |student_caste| %>
  <tr>
    <td><%= student_caste.caste_name %></td>
    <td><%= link_to 'Show', student_caste %></td>
    <td><%= link_to 'Edit', edit_student_caste_path(student_caste) %></td>
    <td><%= link_to 'Destroy', student_caste, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student caste', new_student_caste_path %>

app/views/student_castes/new.html.erb
<h1>New student_caste</h1>

<%= render 'form' %>

<%= link_to 'Back', student_castes_path %>

app/views/student_castes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caste name:</b>
  <%= @student_caste.caste_name %>
</p>


<%= link_to 'Edit', edit_student_caste_path(@student_caste) %> |
<%= link_to 'Back', student_castes_path %>