config/routes.rb
Vpapp::Application.routes.draw do

  resources :countries

  resources :states

  resources :cities

  resources :student_talukas

  resources :student_districts

  resources :yearly_detail_streams

  resources :yearly_detail_courses

  resources :yearly_detail_years

  resources :donor_titles

  resources :donation_purposes

  resources :donation_types

  resources :donation_statuses

  resources :donor_types

  resources :student_area_types

  resources :student_parent_occupations

  resources :student_study_meds

  resources :student_categories

  resources :student_castes

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :donation_year_links

  resources :yearly_details do
    get "upload_yeardata", :on => :collection
    get "upload_validate_yeardata", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "upload_yeardata", :on => :collection
    post "upload_validate_yeardata", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :yearly_details

  get "users/index"
  get "users/new"
  get "users/show"
  get "users/edit"

  resources :students do
    get "upload_student", :on => :collection
    get "upload_validate_student", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_student", :on => :collection
    post "upload_validate_student", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :students

  resources :donations do
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :donations

  get "home/choosepage"

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  devise_for :users
  resources :users

  devise_scope :user do
    get 'users/sign_out', :to => 'devise/sessions#destroy', as: 'destroy_user_session'
  end

  resources :donors do
    get "upload_donor", :on => :collection
    get "upload_validate_donor", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_donor", :on => :collection
    post "upload_validate_donor", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :donors

  get "home/index"

  root :to => 'home#index'

  match ':action' => 'home#:action'
end

app/views/shared/_footer.html.erb
<br />
<div class="footer">
  <p align="center">Copyright 2012 <a href="http://www.vidyaposhak.org.in">VidyaPoshak</a>. All Rights Reserved.</p>
  <p align="center">Powered By: <a href="http://www.distinctnotion.com">Distinct Notion</a></p>
</div>

app/views/shared/_header.html.erb
<h1 class="mainbanner"><%= link_to "Vidya Poshak Management System", root_url %></h1>
<%#- <%= link_to "Vidya Poshak Management System", root_url %>

app/views/shared/_menu.html.erb
	<div class="cssplayMenu niceblue">
		<ul>
			<li><%= link_to "Home", root_url %></li>
			<li><%= link_to "Donors &#8250;".html_safe, donors_path %>
				<ul>
				  <li><%= link_to "List All Donors", donors_path %></li>
					<li><%= link_to "Add New Donor", new_donor_path %></li>
					<li><%= link_to "Search / Edit Donors", search_donors_path %></li>
					<li><%= link_to "Link Donations to Students", new_donation_year_link_path %></li>
			  </ul>
		  </li>

			<li><%= link_to "Students &#8250;".html_safe, students_path %>
				<ul>
				  <li><%= link_to "List All Students", students_path %></li>
					<li><%= link_to "Add New Student", new_student_path %></li>
					<li><%= link_to "Search / Edit Students", search_students_path %></li>
					<li><%= link_to "Link Students to Donations", new_donation_year_link_path %></li>
			  </ul>
		  </li>

			<li><%= link_to "Search and Report &#8250;".html_safe, "#" %>
				<ul>
				  <li><%= link_to "Search Donors", search_donors_path %></li>
					<li><%= link_to "Search Students", search_students_path %></li>
					<li><%= link_to "Search Donations", search_donations_path %></li>
					<li><%= link_to "Search Yearly Detail", search_yearly_details_path %></li>
			   </ul>
		  </li>

		  <% if (user_signed_in?) && (current_user.role == "admin") %>
				<li><%= link_to "DropDowns &#8250;".html_safe, "#" %>
					<ul>
					  <li><%= link_to "&#8249; General".html_safe, "#" %>
							<ul>
								<li><%= link_to "City", cities_path %></li>
								<li><%= link_to "State", states_path %></li>
								<li><%= link_to "Country", countries_path %></li>
							</ul>
						</li>
						<li><%= link_to "&#8249; Student".html_safe, "#" %>
							<ul>
								<li><%= link_to "District", student_districts_path %></li>
								<li><%= link_to "Taluka", student_talukas_path %></li>
								<li><%= link_to "Caste", student_castes_path %></li>
								<li><%= link_to "Category", student_categories_path %></li>
								<li><%= link_to "Area Type", student_area_types_path %></li>
								<li><%= link_to "Study Medium", student_study_meds_path %></li>
								<li><%= link_to "Parent Occupation", student_parent_occupations_path %></li>
							</ul>
						</li>
						<li><%= link_to "&#8249; Student YearData".html_safe, "#" %>
							<ul>
								<li><%= link_to "Course", yearly_detail_courses_path %></li>
								<li><%= link_to "Stream", yearly_detail_streams_path %></li>
								<li><%= link_to "Year / Result Year", yearly_detail_years_path %></li>
							</ul>
						</li>
						<li><%= link_to "&#8249; Donor".html_safe, "#" %>
							<ul>
								<li><%= link_to "Title", donor_titles_path %></li>
								<li><%= link_to "Donor Type", donor_types_path %></li>
							</ul>
						</li>
						<li><%= link_to "&#8249; Donor Donation".html_safe, "#" %>
							<ul>
								<li><%= link_to "Purpose", donation_purposes_path %></li>
								<li><%= link_to "Donation Type", donation_types_path %></li>
								<li><%= link_to "Status", donation_statuses_path %></li>
							</ul>
						</li>
					</ul>
				</li>
			<% end %>

			<% if (user_signed_in?) && (current_user.role == "super_admin") %>
				<li><%= link_to "Super Admin &#8250;".html_safe, rails_admin_path, :id => "current" %>
					<ul>
						<li><%= link_to "List All Users", users_path %></li>
						<li><%= link_to "Add New User", new_user_path %></li>
						<li><%= link_to "List Donations", donations_path %></li>
						<li><%= link_to "List Yearly Details", yearly_details_path %></li>
						<li><%= link_to "List All Links", donation_year_links_path %></li>
					</ul>
				</li>
			<% end %>

			<% if (user_signed_in?) %>
		  	<li><%= link_to "LOGOUT", destroy_user_session_path, :method => :delete %></li>
			<% else %>
      	<li><%= link_to "LOGIN", new_user_session_path %></li>
			<% end %>

			<li><a href="#">Menu Color &#8250;</a>
			  <ul class="colorScheme">
				  <li class="red"></li>
				  <li class="orange"></li>
				  <li class="yellow"></li>
				  <li class="green"></li>
				  <li class="blue"></li>
				  <li class="indigo"></li>
				  <li class="violet"></li>
				  <li class="grey"></li>
				  <li class="niceblue"></li>
			  </ul>
		  </li>
		  <li><a href="http://distinctnotion.com/index.php/contact">Contact</a>
		</ul>
		<!-- <span><a href="#x">Close X</a></span> -->
	</div>

app/views/shared/_signin_signout.html.erb
<div class="loginout">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %><br />
    You have
    <% if current_user.role != "" %>
      <%= current_user.role.humanize %>
    <% else %>
      General User
    <% end %>
    privilleges.
  <% else %>
    <!-- <%= link_to "Sign Up", new_user_registration_path %> -->
    <%= link_to "Sign In", new_user_session_path %>
  <% end %>
</div>