config/routes.rb
Vpapp::Application.routes.draw do

  resources :countries

  resources :states

  resources :cities

  resources :student_talukas

  resources :student_districts

  resources :yearly_detail_streams

  resources :yearly_detail_courses

  resources :yearly_detail_years

  resources :donor_titles

  resources :donation_purposes

  resources :donation_types

  resources :donation_statuses

  resources :donor_types

  resources :student_area_types

  resources :student_parent_occupations

  resources :student_study_meds

  resources :student_categories

  resources :student_castes

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :donation_year_links

  resources :yearly_details do
    get "upload_yeardata", :on => :collection
    get "upload_validate_yeardata", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "upload_yeardata", :on => :collection
    post "upload_validate_yeardata", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :yearly_details

  get "users/index"
  get "users/new"
  get "users/show"
  get "users/edit"

  resources :students do
    get "upload_student", :on => :collection
    get "upload_validate_student", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_student", :on => :collection
    post "upload_validate_student", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :students

  resources :donations do
    get "search", :on => :collection
    get "search_results", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
  end

  resources :donations

  get "home/choosepage"

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout" }

  devise_for :users
  resources :users

  devise_scope :user do
    get 'users/sign_out', :to => 'devise/sessions#destroy', as: 'destroy_user_session'
  end

  resources :donors do
    get "upload_donor", :on => :collection
    get "upload_validate_donor", :on => :collection
    get "search", :on => :collection
    get "search_results", :on => :collection
    get "remove_all_records", :on => :collection
    post "upload_donor", :on => :collection
    post "upload_validate_donor", :on => :collection
    post "search", :on => :collection
    post "search_results", :on => :collection
    post "remove_all_records", :on => :collection
  end

  resources :donors

  get "home/index"

  root :to => 'home#index'

  match ':action' => 'home#:action'
end

app/models/donation.rb
class Donation < ActiveRecord::Base

  # Donation can be linked to multiple yearly details
  has_many :donation_year_links
  has_many :yearly_details, :through => :donation_year_links, :dependent => :destroy

  # Donation belongs to donor
  belongs_to :donor
end

app/models/donation_type.rb
class DonationType < ActiveRecord::Base
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # CanCan Specific Authorization. Doesn't need instance variables
  # See all first line for actions commented except index
  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /donations
  # GET /donations.json
  def index
  # @donations = Donation.all
    @donations = Donation.order(:created_at).page params[:page]
    @all_donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
      format.xls {
              send_data @all_donations.to_xls(:name => "Donations",
              # :columns => [:name, :address, :age],
              # :headers => ['NAME', 'ADDRESS', 'AGE'],
              :cell_format => {:color => :blue},
              :header_format => {:weight => :bold, :color => :red}),
              :filename => 'All_Donations.xls' }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  #  @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
  #  @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
  #  @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
  #  @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        # Find the donor to redirect to donor show page
        @donor = Donor.find(@donation.donor_id)
        format.html { redirect_to donor_path(@donor), notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
  #  @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
  #  @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :ok }
    end
  end

  # Search and Find relevant records based on query
  # Implemented using ransack gem
  # Before calling the form page, new object of Ransack::Search
  # for specific model needs to be created
  def search
    @search = Ransack::Search.new(Donation)
  end

  # Search Results
  def search_results
    @search = Donation.search(params[:q])
    @donations = @search.result(:distinct => true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
      format.xls {
              send_data @donations.to_xls(:name => "Found_Donations",
              # :columns => [:name, :address, :age],
              # :headers => ['NAME', 'ADDRESS', 'AGE'],
              :cell_format => {:color => :blue},
              :header_format => {:weight => :bold, :color => :red}),
              :filename => 'Found_Donations.xls' }
    end
  end

end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend><%= controller.action_name.humanize %> Donation</legend>
  <% if controller.action_name == "edit" %>
      <%= f.hidden_field :donor_id %>
  <% else %>
    <div class="field">
      <%= f.label :donor_id %>
      <%= f.number_field :donor_id %>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </div>
    <div class="field">
      <%= f.label :purpose %>
      <%= f.collection_select :purpose,
          DonationPurpose.all(:order => 'donation_purpose'),
          :donation_purpose, :donation_purpose,
          :prompt => "Select Purpose", :include_blank => true %>
    </div>
  <%-# Status and Type should be visible only to admins -%>
  <% if can? :create, Donation %>
    <div class="field">
      <%= f.label :status %>
      <%= f.collection_select :status,
          DonationStatus.all(:order => 'donation_status'), :donation_status, :donation_status,
          :prompt => "Select Status", :include_blank => true %>
    </div>
    <div class="field">
      <%= f.label :donation_type %>
      <%= f.collection_select :donation_type,
          DonationType.all(:order => 'donation_type'), :donation_type, :donation_type,
          :prompt => "Select Type", :include_blank => true %>
    </div>
  <% else %>
    <%= f.hidden_field :status, :value => "Donated" %>
    <%= f.hidden_field :donation_type, :value => "Online" %>
  <% end %>
    <div class="field">
      <%= f.label :donation_date %>
      <%= f.date_select :donation_date,
    	  	:start_year => 2001, :end_year => Time.now.year + 1,
          :order => [:day, :month, :year],
          :prompt => true %>
    </div>
    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/donations/_student_index.html.erb
<fieldset>
<legend> This Donation Linked Students</legend>

<table id="donations">
  <tr>
    <th>District</th>
    <th>Taluka</th>
    <th>VP ID</th>
    <th>Student Name</th>
    <th>Father Name</th>
    <th>Date of birth</th>
  </tr>

<% students.each do |student| %>
  <tr>
    <td><%= student.district %></td>
    <td><%= student.taluka %></td>
    <td><%= student.vp_id %></td>
    <td><%= link_to "#{student.first_name} #{student.last_name}", student %></td>
    <td><%= student.father_name %></td>
    <td><%= student.date_of_birth %></td>
  </tr>
<% end %>
</table>
</fieldset>
<br />

app/views/donations/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', :back %>

app/views/donations/index.html.erb
<h1>Listing All Donations</h1>

<%= link_to 'Export to EXCEL', donations_path(request.parameters.merge({:format => :xls})) %>

<hr />
<%= paginate @donations %>
<hr />

<table id="donations">
  <tr>
  <% if current_user.role == "super_admin" %>
    <th>Donation ID</th>
    <th>Donor ID</th>
  <% end %>
    <th>Donor Name</th>
    <th>Amount</th>
    <th>Status</th>
    <th>Donation Type</th>
    <th>Purpose</th>
    <th>Donation Date</th>
    <th>Comment</th>
    <% if can? :update, Donation %>
      <th>Actions</th>
    <% end %>
  </tr>

<% @donations.each do |donation| %>
  <tr>
  <% if current_user.role == "super_admin" %>
    <td><%= donation.id %></td>
    <td><%= donation.donor_id %></td>
  <% end %>
    <td><%= link_to "#{donation.donor.first_name} #{donation.donor.last_name}", donation.donor %></td>
    <td><%= link_to "#{donation.amount}", donation %></td>
    <td><%= donation.status %></td>
    <td><%= donation.donation_type %></td>
    <td><%= donation.purpose %></td>
    <td><%= donation.donation_date %></td>
    <td><%= donation.comment %></td>
    <% if can? :update, Donation %>
      <td>
      <%= link_to 'Edit', edit_donation_path(donation) %>
      <% if can? :destroy, Donation %>
        | <%= link_to 'Destroy', donation, confirm: 'Are you sure?', method: :delete %>
      <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if can? :create, Donation %>
  <%= link_to 'New Donation', new_donation_path %>
<% end %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/donations/search.html.erb
<h1>Search and Find Donations </h1>
<h4 id="alert">Leave fields blank if you don't want them to be used for search</h4>
<%= search_form_for @search, url: search_results_donations_path do |f| %>
  <fieldset>
  <legend>Search Attributes</legend>
  <%= f.label "Amount From" %>
  <%= f.text_field :amount_gteq %>
  <%= f.label "Amount To" %>
  <%= f.text_field :amount_lteq %>

  <%= f.label "Purpose" %>
  <%= f.select(:purpose_matches, %w{Nurture_Merit Library Camp GFS}, :include_blank => true) %>
  <br />
  Donation Type
  <%= f.select(:donation_type_matches, %w{Online Cash Cheque DD}, :include_blank => true) %>
  Status
  <%= f.select(:status_matches, %w{Donated Approved Failed}, :include_blank => true) %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/donations/search_results.html.erb
<h1>DONATION SEARCH RESULTS</h1>

<%= link_to 'Export to EXCEL', search_results_donations_path(request.parameters.merge({:format => :xls})) %>
<br />
<% if current_user.role == "super_admin" %>
  QUERY: <%= @donations.to_sql %>
<% end %>
<hr />

<table id="donations">
  <tr>
  <% if current_user.role == "super_admin" %>
    <th>Donation ID</th>
    <th>Donor ID</th>
  <% end %>
    <th>Donor Name</th>
    <th>Amount</th>
    <th>Status</th>
    <th>Donation Type</th>
    <th>Purpose</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
  <% if current_user.role == "super_admin" %>
    <td><%= donation.id %></td>
    <td><%= donation.donor_id %></td>
  <% end %>
    <td><%= link_to "#{donation.donor.first_name} #{donation.donor.last_name}", donation.donor %></td>
    <td><%= donation.amount %></td>
    <td><%= donation.status %></td>
    <td><%= donation.donation_type %></td>
    <td><%= donation.purpose %></td>
    <td><%= donation.comment %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<% donor = @donation.donor %>
<%= form_for(@donation) do |f| %>
  <fieldset>
  <legend>Donation Details</legend>
    <h3>Donated By: <%= link_to "#{donor.first_name} #{donor.last_name}", donor %></h3>
    <div class="field">
      <%= f.label :amount %>
      <%= f.text_field :amount, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :status %>
      <%= f.text_field :status, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :donation_type %>
      <%= f.text_field :donation_type, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :purpose %>
      <%= f.text_field :purpose, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :donation_date %>
      <%= f.text_field :donation_date, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment, :disabled => true %>
    </div>
    <%= link_to 'Edit', edit_donation_path(@donation) %> |
    <%= link_to 'Back', :back %>
  </fieldset>
<% end %>

<% all_student_ids = [] %>
<% yearly_details = @donation.yearly_details %>
<% yearly_details.each do |this_yearly_detail| %>
  <% unless all_student_ids.include?(this_yearly_detail.student_id) %>
    <% all_student_ids << this_yearly_detail.student_id %>
  <% end %>
<% end %>

<%= render :partial => 'student_index', :locals => {:students=>Student.find_all_by_id(all_student_ids).uniq} %>